# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DemoApp' do
  use_frameworks!

  # Pods for DemoApp
  pod 'Mux-Stats-Kaltura', :path => '../../'

  target 'DemoAppUITests' do
    # Pods for testing
  end

end
