target 'DemoApp' do
  platform :ios, '11.0'
  use_frameworks!

  # Pods for DemoApp
  pod 'Mux-Stats-Kaltura', :path => '../../'

  target 'DemoAppUITests' do
    # Pods for testing
  end
end

target 'DemoAppTvOS' do
  platform :tvos, '11.0'
  use_frameworks!
  pod 'Mux-Stats-Kaltura', :path => '../../'
end
