
target 'MUXSDKKaltura' do
  platform :ios, '11.0'
  use_frameworks!
  
  # Pods for MUXSDKKaltura
  pod 'Mux-Stats-Core', '4.5.2'
  pod 'PlayKit'

  target 'MUXSDKKalturaTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mux-Stats-Core', '4.5.2'
    pod 'PlayKit'
  end
end

target 'MUXSDKKalturaTv' do
  platform :tvos, '11.0'
  use_frameworks!
  
  # Pods for MUXSDKKalturaTv
  pod 'Mux-Stats-Core', '4.5.2'
  pod 'PlayKit'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
