name: Validate release

on:
  push:
    branches:
      - 'releases/**'

jobs:
  version-check:
    name: Validate Versions
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Version Check Script
        run: ./scripts/version-check.sh Mux-Stats-Kaltura.podspec
  validate-cocoapods:
    name: Validate Podspec
    runs-on: macos-14
    steps:
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Use Xcode 15.3
        run: sudo xcodebuild -s /Applications/Xcode_15.3.app
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Validate Podspec"
        run: "scripts/validate-podspec.sh"
